<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitef522751d2ed991935e30229637cf446
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twilio\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twilio\\' => 
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/src/Twilio',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitef522751d2ed991935e30229637cf446::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitef522751d2ed991935e30229637cf446::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
